### PR TITLE
Update Chinese translation for Cinnamon Tweak

### PR DESCRIPTION
**Pull request by giwhub**

### CODE REVIEW

**Comment by Odyseus** [comment]
Hello, @giwhub.

Can you *rebase* this pull request? It seems that something went wrong when I rewrote the history of the repository.

**Comment by giwhub** [comment]
Sure.

**Comment by Odyseus** [comment]
Thanks, @giwhub. And sorry for the inconvenience. 👍

**Comment by giwhub** [comment]
That's fine.

**Pull request closed without merging**
