### PR TITLE
Create sv.po

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation

### CODE REVIEW

**Comment by Odyseus** [comment]
Hello, @eson57.

It seems that something went wrong when I rewrote the history of the repository. Can you create another pull request? You will need to *rebase* the master branch of your fork.

**Comment by eson57** [comment]
Ok...

**Comment by Odyseus** [comment]
Thanks, @eson57. And sorry for the inconvenience. 👍

**Comment by eson57** [comment]
No problem!

**Pull request closed without merging**
