### PR TITLE
PopupTranslator new ru.po

### PR DESCRIPTION
**Pull request by Ilis**
One more try

### CODE REVIEW

**Comment by Odyseus** [comment]
I'm still seeing the three commits that shouldn't be in there.

screenshot from 2017-05-07 10-44-08

I recommend you to follow the wiki that I linked to you before. If you still can't fix it, just let me know. I already downloaded the **ru.po** file and I can upload it in a new commit.

**Comment by Ilis** [comment]
I have “rejected” when trying to push my branch with po after all steps including rebase :)

ilis@deore ~/git/CinnamonTools $ git push origin popuptranslator_ru_po_3
To https://github.com/Ilis/CinnamonTools.git
 ! [rejected]        popuptranslator_ru_po_3 -> popuptranslator_ru_po_3 (non-fast-forward)

**Comment by Ilis** [comment]
> If you still can't fix it, just let me know. I already downloaded the ru.po file and I can upload it in a new commit.

Yes, I can't :)

Please, upload my file manually!

**Comment by Ilis** [comment]
One more fetch, merge, rebase, pull, push, etc. :)

**Comment by Odyseus** [comment]
I was about to suggest to you another thing. You can create a pull requests directly from the GitHub pages. You can go to the folder you want to add the file to, click the **Upload files** button and upload your file. Done. No need to clone the repository locally on your computer (although, you do need to have it forked on your account to be able to create pull requests). It's perfect for translators because normally you have to deal with just one file.

I have no idea why you get "rejected". Like I said, I'm not a pro. 90% of the time, I don't even use git from the command line (I use git-gui).

I have set up all my repositories and the ones that I contribute into exactly as I describe in the wiki of this repository, and I never had problems.

All of this is my fault, of course. I caused it by rewriting the history of my repository to edit a couple of commit messages. So, my apologies for that.

I committed your translation for Popup Translator applet. Thanks again for your contribution. 👍

**Pull request closed without merging**
