### PR TITLE
PopupTranslator new ru.po

### PR DESCRIPTION
**Pull request by Ilis**

### CODE REVIEW

**Comment by Odyseus** [comment]
Thanks for your contribution, @Ilis.

Could you rebase your pull request? It seems that you cloned my repository just before I had rewritten its history.

**Comment by Ilis** [comment]
Hm. I'm not pro in git...

I've did pull upstream and push my branch again. Hope, it's help :)

**Comment by Odyseus** [comment]
I'm not a pro neither. LOL

I'm still seeing three commits that shouldn't be in your pull request. What I do is to use the `git rebase`  command, I never used `merge`.

In [this repository's wiki](https://github.com/Odyseus/CinnamonTools/wiki/GitHub-tips-&-tricks#keep-your-forked-repositories-synchronized-with-the-original-repositories) I describe the basic steps. But it depends on how you have your local fork set up.

You can always close this PR, re-clone the repository and create a new PR if you feel like you *got lost*.

**Comment by Ilis** [comment]
Made another PR

**Pull request closed without merging**
